version: 2.1
orbs: 
    python: circleci/python@2.0.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run: 
          command: |
            pip install pytest
            pytest --junitxml=test-results/junit.xml TestTriangle.py
      - store_test_results:
          path: test-results
workflows:
  testHW2:
    jobs:
      - build